### ISSUE TITLE
Intro docs should indicate that Node.js v14.x is required

### ISSUE THREAD

**Issue by grempe** [assaf/queue-run#52]
Installation in a clean dir throws warnings if not using outdated LTS version 14.x. I suspect this is the case since the AWS Lambda runtime doesn't seem to support v16.x LTS runtime yet. This results in a warning on install.

```
~/ 🤖 v16.13.2 via 🎁 v1.0.0
❯ npm install -D queue-run
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'queue-run@0.13.0',
npm WARN EBADENGINE   required: { node: '14.x' },
npm WARN EBADENGINE   current: { node: 'v16.13.2', npm: '8.5.2' }
npm WARN EBADENGINE }

added 32 packages, and audited 33 packages in 4s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I would suggest that the intro docs [https://queue.run/](https://queue.run/) should indicate that this is the required version before getting started (and say why).

**Comment by assaf** [comment]
Added note in the deploy section: https://queue.run/deploying

**Comment by grempe** [comment]
Perfect.
