### ISSUE TITLE
CloudFormation

### ISSUE THREAD

**Issue by assaf** [assaf/queue-run#54]
QueueRun can use CloudFormation for the following use cases:

- Specification so you can inspect what gets deployed
- Replace code, make further feature development and collaboration easier
- Enable integration with a larger stack

On the first point, generating CF document is possible, but it won’t be complete/correct unless it’s also used for deployment.

On the second point, even if we can only use CF for 80% of the deployment (see below), it could simplify the code base: easier to add features, and easier for collaborators to get involved.

On the third point, not clear how/if this makes a difference.

---

We can use CF but not for everything.

To deploy a Lambda function with CF, the function must be uploaded to S3. That would require the developer to create/select S3 bucket, which adds another step to the initial deployment, and one more artifact that needs to be managed.

Alternatively, we can deploy Lambda function directly as we do today, and use CF for all other resources (queues, schedules, tables, etc).

To support HTTP/WS API, the backend needs to know which URL it’s available on, so it can generate absolute URLs. Right now:

- Deployment starts by creating an API (first time only)
- Deployment looks up the API, convert to URLs
- These URLs are available to Lambda function as environment variables
- Deploy Lambda function with the environment variable
- Add integrations, routes, etc to the API (this can be done with CF)

This brings us to the second issue: environment variables. These should be shared by all deployers, so stored in AWS and pulled down during deployment. So that resource (table) needs to exist outside of CF, generated by the `env` command.

Regarding custom domains. As with environment variables, this association needs to reside in AWS, so the process for adding custom domains also exists outside of CF.

Everything else though can safely move to CF.

**Comment by assaf** [comment]
https://github.com/assaf/queue-run/tree/cloudformation

**Comment by sujal** [comment]
I've been traveling, but excited to see this. Will review when I'm back home this weekend.

**Comment by sujal** [comment]
Curious on your thinking on the two things that aren't in cloudformation. 

I see the issue with the lambda deploy stuff. At the same time I'd love to see everything in a cloudformation stack, even if it were more than one stack.

Would you be willing to consider a patch that uses 2-3 stacks that link inputs and outputs together?

Something like:

* deploy infra stack: S3 bucket, deployment dynamodb
* lambda stack: lambda, roles, gateway, etc
* domain stack: (if necessary/worthwhile)

I have not looked deeply at the domain stuff yet. My use case specifically is to integrate the lambda & gateway into an existing terraformed environment, with domains, certs, etc all managed by TF, so I don't have strong feelings about it being in a CF stack. I'm not going to use it for now.

There's nothing wrong with having multiple stacks and using the input/output vars to link them together. It's how lots of infra is deployed at my former day job (though we were moving to TF there, too).

That said, I want to make sure this fits the philosophy of the framework. I'll dig in a bit and see if I can refactor this. I do need to remember how to redeploy new code for lambdas using CF, so maybe I'll run into problems I'm not thinking about yet.

**Comment by sujal** [comment]
Thinking about this more, as long as the endpoints and integration points of the underlying AWS infra is well defined, maybe CF is overkill. In a non-CF case, all I'd really want is a destroy and a describe function as part of the underlying QR CLI. Maybe that's all that's needed for now. At that point, it works just like serverless.js and other frameworks.

Would that be a better approach? If things change that impact the other infrastructure I have in Terraform or Cloudformation, then that's on the developer to manually coordinate deployment changes. 

Beyond the two commands above, I feel like splitting into multiple lambdas or some of the other ideas in the issues or that you've hinted at are probably more important than CF itself.

**Comment by assaf** [comment]
This branch includes a `delete` command. There's a `status` command that should give you just enough information, and can always add more details.

I'm pretty sure you don't need two stacks to deploy the Lambda function. If you can do it in two stacks, you can do it with one stack. You can add to the stack and  update it.

With custom domains, the issue is managing state, which includes some manual tasks. The post-CF approach follows the same model as the pre-CF approach, and neither is perfect. There's a better solution. It has not presented itself yet :)

**Comment by sujal** [comment]
Will this get merged into main as is, then? I love having the commands and being able to look at the stack in Cloudformation.

I have some other ideas, but have been short on time. I am back to my semi-employed state this week without a lot of family stuff, so hopefully I'll be able to share a pull request soon. None of it takes away any value from what you've added here, though - I just have a thought about trying to deploy the lambda itself, and want to define some outputs on the stack so it's easier for other templates to use what's created by this stack.

**Comment by assaf** [comment]
Just published 0.14.

I made a couple of changes. The Cloudformation template is now generated when running the deploy command, saving a copy to `.queue-run/.cloudformation.json`. This means it has access to deploy information (account id, region, etc), don't need to make excessive use of variables and CF functions.
